language: csharp
solution: GCodeNet.sln
install:
  - nuget restore GCodeNet.sln
  - nuget install NUnit.Console -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release GCodeNet.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./UnitTests/bin/Release/TestProject.dll